name: Sync Code Updates to Self-Hosted Runner

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-eks/**'


jobs:
  sync:
    runs-on: [self-hosted, linux, x64]

    steps:
      # 1️⃣ Checkout entire repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history so git diff works correctly

      # 2️⃣ Detect changed files
      - name: Detect changed files
        id: changes
        run: |
          echo "🔍 Detecting changed files..."
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Save to output for later steps
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 3️⃣ Sync changes to runner project directory
      - name: Sync changed files to project folder
        run: |
          PROJECT_DIR="/opt/github/projects/${{ github.repository }}"
          echo "📂 Target project directory: $PROJECT_DIR"

          # Create directory if first time
          mkdir -p "$PROJECT_DIR"

          # Copy each changed file to target directory
          echo "${{ steps.changes.outputs.changed_files }}" | while read file; do
            if [ -n "$file" ]; then
              SRC_PATH="$file"
              DEST_PATH="$PROJECT_DIR/$file"
              DEST_DIR=$(dirname "$DEST_PATH")

              mkdir -p "$DEST_DIR"
              cp -r "$SRC_PATH" "$DEST_PATH"

              echo "✅ Updated: $file"
            fi
          done

          echo "✅ All changed files have been updated in $PROJECT_DIR"
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      # 4️⃣ Print result summary
      - name: Summary
        run: |
          echo "## 🧩 Code Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- Updated folder: $PROJECT_DIR" >> $GITHUB_STEP_SUMMARY
          echo "- Changed files:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.changes.outputs.changed_files }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
