name: Sync Code Updates to Self-Hosted Runner

on:
  push:
    branches:
      - main


jobs:
  sync:
    runs-on: [self-hosted, linux, x64]

    steps:
      # 1️⃣ Checkout entire repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history so git diff works correctly

      
