name: Terraform Deploy

on:
  repository_dispatch:
    types: [bootstrap_completed]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Plan
        run: terraform plan -var-file="envs/${{ github.event.client_payload.environment }}.tfvars" -out=tfplan.out

      - name: Terraform Apply
        run: terraform apply -var-file="envs/${{ github.event.client_payload.environment }}.tfvars" -auto-approve
