name: Terraform Deploy

on:
  repository_dispatch:
    types: [bootstrap_completed]

jobs:
  terraform:
    runs-on: [self-hosted, linux, x64]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Verify Project Directory
        run: |
          echo "📂 Verifying project directory: ${{ github.event.client_payload.repo_path }}"
          ls -la ${{ github.event.client_payload.repo_path }}
          echo "✅ Project directory verified"

      - name: Verify AWS Credentials
        run: |
          echo "🔍 Verifying AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials validated"

      - name: Initialize Terraform Backend
        run: |
          echo "🚀 Initializing Terraform backend..."
          cd ${{ github.event.client_payload.repo_path }}

          # Check required files
          for file in backend-config/${{ github.event.client_payload.environment }}.tfbackend static.tfvars envs/${{ github.event.client_payload.environment }}.tfvars; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done

          # Initialize Terraform
          terraform init -backend-config="backend-config/${{ github.event.client_payload.environment }}.tfbackend"

          # Select or create workspace
          terraform workspace select ${{ github.event.client_payload.environment }} || terraform workspace new ${{ github.event.client_payload.environment }}

          echo "✅ Terraform initialized successfully."
        working-directory: ${{ github.event.client_payload.repo_path }}

      - name: Terraform Validate
        run: |
          echo "🔍 Validating Terraform configuration..."
          terraform validate
          echo "✅ Validation passed!"
        working-directory: ${{ github.event.client_payload.repo_path }}

      - name: Terraform Plan
        run: |
          echo "📋 Running Terraform plan..."
          terraform plan \
            -var-file="static.tfvars" \
            -var-file="envs/${{ github.event.client_payload.environment }}.tfvars" \
            -out=tfplan.out
          echo "✅ Terraform plan completed."
        working-directory: ${{ github.event.client_payload.repo_path }}

      - name: Terraform Apply
        run: |
          echo "🚀 Applying Terraform changes..."
          export TF_LOG=INFO
          terraform apply -auto-approve tfplan.out
          echo "✅ Terraform apply completed successfully!"
        working-directory: ${{ github.event.client_payload.repo_path }}
        timeout-minutes: 120

      - name: Output EKS Cluster Info
        run: |
          echo "🎉 EKS Cluster deployment completed!"
          terraform output
        working-directory: ${{ github.event.client_payload.repo_path }}

      - name: Deployment Summary
        run: |
          echo "## 🎉 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ github.event.client_payload.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Region:** ${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Workspace:** ${{ github.event.client_payload.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ✅ Successfully deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Terraform Outputs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        working-directory: ${{ github.event.client_payload.repo_path }}
